### ISSUE TITLE
stuck at splashscreen

### ISSUE THREAD

**Issue by pew** [meteocool/ios#131]
Not sure how to reproduce, don't open the app for a day? It'll stay like this forever until you force-quit.

![Screenshot 2021-04-07 at 6 10 01 AM](https://user-images.githubusercontent.com/52463/113809288-159dfb00-9768-11eb-99f8-f8a632b3f0fc.png)

**Comment by v4lli** [comment]
Haven't seen this in a while, please re-open if it happens again
