### ISSUE TITLE
Blured bar too tall on devices without rounded corners

### ISSUE THREAD

**Issue by v4lli** [meteocool/ios#36]
<img width="630" alt="Screen Shot 2021-01-02 at 17 59 39" src="https://user-images.githubusercontent.com/1577223/103462260-4b27e800-4d24-11eb-9a7d-3915796f676b.png">

**Comment by v4lli** [comment]
@Nina2244 any ideas?

**Comment by Nina2244** [comment]
Ja ist mir auch schon aufgefallen... man könnte des je nach Geräte Typ machen aber ist halt auch unschön ...
