### ISSUE TITLE
Push token info label overlaps with value label

### ISSUE THREAD

**Issue by Flowm** [meteocool/ios#44]
![86571511-265D-4DA3-82A2-96ED27D683A1_1_105_c](https://user-images.githubusercontent.com/1117666/104131755-bbfc7f00-5378-11eb-9c0c-af17d118f580.jpeg)

**Comment by v4lli** [comment]
Since the push token is not copy'able anyway, and it's also in the feedback email, should we maybe remove/comment out this row @Nina2244?

**Comment by Nina2244** [comment]
I will delete it.
